// Sample cases for the Generate case button.
//
// Every entry is a real record from the training data, expressed in the
// application's input schema, with panels the record does not cover left at a
// normal adult reading. Nothing here is invented.
//
// Positives are sampled evenly across each model's probability range rather than
// taking the most confident record, so a generated case lands anywhere from the
// fifties to the high nineties instead of always reading 99. Negative records are
// included too, so some generated cases come back clean. Every case was scored
// before being written here, and only kept if the panel that comes out on top
// matches the expectation shown to the user.
//
// Generated by make_cases.py. Regenerate if the models are retrained.

export type CaseValues = Record<string, number>;

export const NORMAL: CaseValues = {
  age: 55,
  bmi: 24.1,
  wbc: 6.4,
  rbc: 4.7,
  hemoglobin: 14,
  platelets: 250,
  glucose: 88,
  calcium: 9.4,
  bun: 14,
  creatinine: 0.9,
  protein_total: 7,
  albumin: 4.4,
  ast: 22,
  alt: 20,
  bilirubin: 0.6,
  alkaline_phosphatase: 78,
  alpha_fetoprotein_level: 3.1,
  psa: 0.9,
  plasma_ca19_9: 12,
  radius_mean: 11.4,
  texture_mean: 17.2,
  perimeter_mean: 72.6,
  area_mean: 400,
  gender: 0,
  smoking: 0,
  alcohol_intake: 0.5,
  physical_activity: 6,
  hepatitis_b: 0,
  hepatitis_c: 0,
  diabetes: 0,
};

export type DemoCase = {
  id: string;
  domain: string;
  expect: string;
  positive: boolean;
  source: string;
  note: string;
  delta: CaseValues;
};

export const CASE_POOL: DemoCase[] = [
  {
    id: "general-neg-0",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "21 year old man, never smoked. BMI 25.03, 6 hours of exercise a week, alcohol 2 of 5.",
    delta: { age: 21, bmi: 25.03, gender: 1, alcohol_intake: 2 },
  },
  {
    id: "general-neg-1",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "22 year old man, never smoked. BMI 21.84, 6 hours of exercise a week, alcohol 5 of 5.",
    delta: { age: 22, bmi: 21.84, gender: 1, alcohol_intake: 5 },
  },
  {
    id: "general-neg-2",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "20 year old man, never smoked. BMI 28.48, 6 hours of exercise a week, alcohol 4 of 5.",
    delta: { age: 20, bmi: 28.48, gender: 1, alcohol_intake: 4 },
  },
  {
    id: "breast-3",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 13.48 and an area of 559.2. Blood work is normal.",
    delta: { radius_mean: 13.48, texture_mean: 20.82, perimeter_mean: 88.4, area_mean: 559.2 },
  },
  {
    id: "breast-4",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 14.71 and an area of 656.9. Blood work is normal.",
    delta: { radius_mean: 14.71, texture_mean: 21.59, perimeter_mean: 95.55, area_mean: 656.9 },
  },
  {
    id: "breast-5",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 13.82 and an area of 595.9. Blood work is normal.",
    delta: { radius_mean: 13.82, texture_mean: 24.49, perimeter_mean: 92.33, area_mean: 595.9 },
  },
  {
    id: "breast-6",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 15.08 and an area of 716.6. Blood work is normal.",
    delta: { radius_mean: 15.08, texture_mean: 25.74, perimeter_mean: 98, area_mean: 716.6 },
  },
  {
    id: "breast-7",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 15.1 and an area of 712.8. Blood work is normal.",
    delta: { radius_mean: 15.1, texture_mean: 22.02, perimeter_mean: 97.26, area_mean: 712.8 },
  },
  {
    id: "breast-8",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 17.3 and an area of 928.2. Blood work is normal.",
    delta: { radius_mean: 17.3, texture_mean: 17.08, perimeter_mean: 113, area_mean: 928.2 },
  },
  {
    id: "breast-9",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 16.02 and an area of 797.8. Blood work is normal.",
    delta: { radius_mean: 16.02, texture_mean: 23.24, perimeter_mean: 102.7, area_mean: 797.8 },
  },
  {
    id: "breast-neg-10",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 9.504 and an area of 273.9. Blood work is normal.",
    delta: { radius_mean: 9.504, texture_mean: 12.44, perimeter_mean: 60.34, area_mean: 273.9 },
  },
  {
    id: "breast-neg-11",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 6.981 and an area of 143.5. Blood work is normal.",
    delta: { radius_mean: 6.981, texture_mean: 13.43, perimeter_mean: 43.79, area_mean: 143.5 },
  },
  {
    id: "breast-neg-12",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 11.43 and an area of 398. Blood work is normal.",
    delta: { radius_mean: 11.43, texture_mean: 17.31, perimeter_mean: 73.66, area_mean: 398 },
  },
  {
    id: "liver-13",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "49 year old woman with hepatitis C. AFP at 3.1 ng/mL.",
    delta: { age: 49, protein_total: 7.7, albumin: 3.9, ast: 37, alt: 28, alkaline_phosphatase: 99, hepatitis_c: 1 },
  },
  {
    id: "liver-14",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "56 year old man with hepatitis C. AFP at 3.1 ng/mL.",
    delta: { age: 56, protein_total: 7.4, albumin: 3.7, ast: 46, alt: 62, alkaline_phosphatase: 74, gender: 1, hepatitis_c: 1 },
  },
  {
    id: "liver-15",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "61 year old man with hepatitis C, diabetes. AFP at 3.1 ng/mL.",
    delta: { age: 61, protein_total: 7.6, albumin: 3.3, ast: 88, alt: 83, bilirubin: 0.7, alkaline_phosphatase: 38, gender: 1, hepatitis_c: 1, diabetes: 1 },
  },
  {
    id: "liver-16",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "59 year old man with hepatitis C. AFP at 3.1 ng/mL.",
    delta: { age: 59, protein_total: 7.3, albumin: 3.6, ast: 51, alt: 56, bilirubin: 0.9, alkaline_phosphatase: 127, gender: 1, hepatitis_c: 1 },
  },
  {
    id: "liver-17",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "60 year old man with hepatitis C. AFP at 3.1 ng/mL.",
    delta: { age: 60, protein_total: 8.9, albumin: 3.4, ast: 61, alt: 49, bilirubin: 1.4, alkaline_phosphatase: 98, gender: 1, hepatitis_c: 1 },
  },
  {
    id: "liver-18",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "61 year old man with hepatitis C, diabetes. AFP at 3.1 ng/mL.",
    delta: { age: 61, albumin: 3.4, ast: 55, alt: 73, bilirubin: 0.8, alkaline_phosphatase: 75, gender: 1, hepatitis_c: 1, diabetes: 1 },
  },
  {
    id: "liver-19",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "NHANES 2005-2018, US adults, positive record",
    note: "65 year old man with hepatitis C, diabetes. AFP at 3.1 ng/mL.",
    delta: { age: 65, protein_total: 7.1, albumin: 3.5, ast: 67, alt: 50, alkaline_phosphatase: 96, gender: 1, hepatitis_c: 1, diabetes: 1 },
  },
  {
    id: "liver-neg-20",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "24 year old woman with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 24, protein_total: 6.2, albumin: 3.2, alt: 21, bilirubin: 0.4, alkaline_phosphatase: 121 },
  },
  {
    id: "liver-neg-21",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "21 year old woman with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 21, protein_total: 6, albumin: 2.8, ast: 19, alt: 13, bilirubin: 0.2, alkaline_phosphatase: 67 },
  },
  {
    id: "liver-neg-22",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "NHANES 2005-2018, US adults, negative record",
    note: "25 year old woman with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 25, protein_total: 5.4, albumin: 2.6, ast: 23, alt: 14, bilirubin: 0.3, alkaline_phosphatase: 166 },
  },
  {
    id: "pancreatic-23",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "73 year old man. CA 19-9 at 263.954 U/mL, bilirubin 2.7186, glucose 120.34, creatinine 1.212.",
    delta: { age: 73, glucose: 120.34, creatinine: 1.212, bilirubin: 2.7186, plasma_ca19_9: 263.9545, gender: 1 },
  },
  {
    id: "pancreatic-24",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "75 year old man. CA 19-9 at 248.411 U/mL, bilirubin 2.5663, glucose 97.2, creatinine 1.4591.",
    delta: { age: 75, glucose: 97.2, creatinine: 1.4591, bilirubin: 2.5663, plasma_ca19_9: 248.4114, gender: 1 },
  },
  {
    id: "pancreatic-25",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "31 year old man. CA 19-9 at 334.735 U/mL, bilirubin 1.6069, glucose 99.93, creatinine 1.5987.",
    delta: { age: 31, glucose: 99.93, creatinine: 1.5987, bilirubin: 1.6069, plasma_ca19_9: 334.7348, gender: 1 },
  },
  {
    id: "pancreatic-26",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "49 year old woman. CA 19-9 at 303.428 U/mL, bilirubin 3.2066, glucose 130.85, creatinine 1.3822.",
    delta: { age: 49, glucose: 130.85, creatinine: 1.3822, bilirubin: 3.2066, plasma_ca19_9: 303.4284 },
  },
  {
    id: "pancreatic-27",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "74 year old woman. CA 19-9 at 461.786 U/mL, bilirubin 1.0744, glucose 122.54, creatinine 1.6178.",
    delta: { age: 74, glucose: 122.54, creatinine: 1.6178, bilirubin: 1.0744, plasma_ca19_9: 461.786 },
  },
  {
    id: "pancreatic-28",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "50 year old woman. CA 19-9 at 377.127 U/mL, bilirubin 2.3407, glucose 83.7, creatinine 1.3564.",
    delta: { age: 50, glucose: 83.7, creatinine: 1.3564, bilirubin: 2.3407, plasma_ca19_9: 377.1267 },
  },
  {
    id: "pancreatic-29",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "31 year old man. CA 19-9 at 310.02 U/mL, bilirubin 2.8241, glucose 68.24, creatinine 1.6912.",
    delta: { age: 31, glucose: 68.24, creatinine: 1.6912, bilirubin: 2.8241, plasma_ca19_9: 310.0204, gender: 1 },
  },
  {
    id: "pancreatic-neg-30",
    domain: "Pancreatic",
    expect: "No cancer detected",
    positive: false,
    source: "Pancreatic biomarker cohort, negative record",
    note: "64 year old man. CA 19-9 at 91.2875 U/mL, bilirubin 1.0505, glucose 111.77, creatinine 0.8561.",
    delta: { age: 64, glucose: 111.77, creatinine: 0.8561, bilirubin: 1.0505, plasma_ca19_9: 91.2875, gender: 1 },
  },
  {
    id: "pancreatic-neg-31",
    domain: "Pancreatic",
    expect: "No cancer detected",
    positive: false,
    source: "Pancreatic biomarker cohort, negative record",
    note: "82 year old man. CA 19-9 at 9.1618 U/mL, bilirubin 0.7391, glucose 98.74, creatinine 0.9238.",
    delta: { age: 82, glucose: 98.74, creatinine: 0.9238, bilirubin: 0.7391, plasma_ca19_9: 9.1618, gender: 1 },
  },
  {
    id: "pancreatic-neg-32",
    domain: "Pancreatic",
    expect: "No cancer detected",
    positive: false,
    source: "Pancreatic biomarker cohort, negative record",
    note: "64 year old man. CA 19-9 at 106.631 U/mL, bilirubin 0.4227, glucose 95.29, creatinine 0.7647.",
    delta: { age: 64, glucose: 95.29, creatinine: 0.7647, bilirubin: 0.4227, plasma_ca19_9: 106.631, gender: 1 },
  },
];

export const caseValues = (c: DemoCase): CaseValues => ({ ...NORMAL, ...c.delta });

/** Draw a random case, never the same one twice in a row. */
export function randomCase(previousId?: string): DemoCase {
  const options = CASE_POOL.filter(c => c.id !== previousId);
  return options[Math.floor(Math.random() * options.length)];
}

/**
 * The case the page opens on. Fixed rather than random so the first render
 * matches between server and client. Every press of Generate case after that
 * draws at random.
 */
export const OPENING_CASE = CASE_POOL.find(c => c.id === "breast-7")!;
