// Sample cases for the Generate case button.
//
// Every entry is a real record from the training data, expressed in the
// application's input schema, with panels the record does not cover left at a
// normal adult reading. Nothing here is invented.
//
// Positives are sampled evenly across each model's probability range rather than
// taking the most confident record, so a generated case lands anywhere from the
// fifties to the high nineties instead of always reading 99. Negative records are
// included too, so some generated cases come back clean. Every case was scored
// before being written here, and only kept if the panel that comes out on top
// matches the expectation shown to the user.
//
// Generated by make_cases.py. Regenerate if the models are retrained.

export type CaseValues = Record<string, number>;

export const NORMAL: CaseValues = {
  age: 55,
  bmi: 24.1,
  wbc: 6.4,
  rbc: 4.7,
  hemoglobin: 14,
  platelets: 250,
  glucose: 88,
  calcium: 9.4,
  bun: 14,
  creatinine: 0.9,
  protein_total: 7,
  albumin: 4.4,
  ast: 22,
  alt: 20,
  bilirubin: 0.6,
  alkaline_phosphatase: 78,
  alpha_fetoprotein_level: 3.1,
  psa: 0.9,
  plasma_ca19_9: 12,
  radius_mean: 11.4,
  texture_mean: 17.2,
  perimeter_mean: 72.6,
  area_mean: 400,
  gender: 0,
  smoking: 0,
  alcohol_intake: 0.5,
  physical_activity: 6,
  genetic_risk: 0,
  cancer_history: 0,
  family_history_cancer: 0,
  hepatitis_b: 0,
  hepatitis_c: 0,
  cirrhosis_history: 0,
  diabetes: 0,
};

export type DemoCase = {
  id: string;
  domain: string;
  expect: string;
  positive: boolean;
  source: string;
  note: string;
  delta: CaseValues;
};

export const CASE_POOL: DemoCase[] = [
  {
    id: "general-0",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "48 year old woman, never smoked, inherited risk medium. BMI 21.2617, 1.25089 hours of exercise a week.",
    delta: { age: 48, bmi: 21.2617, alcohol_intake: 3.6246, physical_activity: 1.2509, genetic_risk: 1 },
  },
  {
    id: "general-1",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "24 year old woman, never smoked, inherited risk low. BMI 29.2936, 5.56818 hours of exercise a week.",
    delta: { age: 24, bmi: 29.2936, alcohol_intake: 3.1502, physical_activity: 5.5682 },
  },
  {
    id: "general-2",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "34 year old man, never smoked, inherited risk medium, previous cancer diagnosis on record. BMI 15.0338, 1.47454 hours of exercise a week.",
    delta: { age: 34, bmi: 15.0338, gender: 1, alcohol_intake: 4.4456, physical_activity: 1.4745, genetic_risk: 1, cancer_history: 1 },
  },
  {
    id: "general-3",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "71 year old man, current smoker, inherited risk low. BMI 34.7246, 1.91106 hours of exercise a week.",
    delta: { age: 71, bmi: 34.7246, gender: 1, smoking: 2, alcohol_intake: 1.1342, physical_activity: 1.9111 },
  },
  {
    id: "general-4",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "66 year old woman, current smoker, inherited risk low. BMI 30.8536, 3.32001 hours of exercise a week.",
    delta: { age: 66, bmi: 30.8536, smoking: 2, alcohol_intake: 0.2613, physical_activity: 3.32 },
  },
  {
    id: "general-5",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "23 year old man, current smoker, inherited risk high, previous cancer diagnosis on record. BMI 20.2999, 3.14434 hours of exercise a week.",
    delta: { age: 23, bmi: 20.2999, gender: 1, smoking: 2, alcohol_intake: 0.7788, physical_activity: 3.1443, genetic_risk: 2, cancer_history: 1 },
  },
  {
    id: "general-6",
    domain: "General",
    expect: "General",
    positive: true,
    source: "General cancer risk cohort, positive record",
    note: "64 year old man, never smoked, inherited risk low, previous cancer diagnosis on record. BMI 27.0336, 6.06716 hours of exercise a week.",
    delta: { age: 64, bmi: 27.0336, gender: 1, alcohol_intake: 2.9972, physical_activity: 6.0672, cancer_history: 1 },
  },
  {
    id: "general-neg-7",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "General cancer risk cohort, negative record",
    note: "28 year old man, never smoked, inherited risk low. BMI 23.1083, 5.44825 hours of exercise a week.",
    delta: { age: 28, bmi: 23.1083, gender: 1, alcohol_intake: 1.9859, physical_activity: 5.4482 },
  },
  {
    id: "general-neg-8",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "General cancer risk cohort, negative record",
    note: "45 year old man, never smoked, inherited risk low. BMI 15.5899, 9.12255 hours of exercise a week.",
    delta: { age: 45, bmi: 15.5899, gender: 1, alcohol_intake: 2.4786, physical_activity: 9.1225 },
  },
  {
    id: "general-neg-9",
    domain: "General",
    expect: "No cancer detected",
    positive: false,
    source: "General cancer risk cohort, negative record",
    note: "24 year old man, never smoked, inherited risk low. BMI 19.9804, 7.49726 hours of exercise a week.",
    delta: { age: 24, bmi: 19.9804, gender: 1, alcohol_intake: 1.0709, physical_activity: 7.4973 },
  },
  {
    id: "breast-10",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 13.48 and an area of 559.2. Blood work is normal.",
    delta: { radius_mean: 13.48, texture_mean: 20.82, perimeter_mean: 88.4, area_mean: 559.2 },
  },
  {
    id: "breast-11",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 14.71 and an area of 656.9. Blood work is normal.",
    delta: { radius_mean: 14.71, texture_mean: 21.59, perimeter_mean: 95.55, area_mean: 656.9 },
  },
  {
    id: "breast-12",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 13.82 and an area of 595.9. Blood work is normal.",
    delta: { radius_mean: 13.82, texture_mean: 24.49, perimeter_mean: 92.33, area_mean: 595.9 },
  },
  {
    id: "breast-13",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 15.08 and an area of 716.6. Blood work is normal.",
    delta: { radius_mean: 15.08, texture_mean: 25.74, perimeter_mean: 98, area_mean: 716.6 },
  },
  {
    id: "breast-14",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 15.1 and an area of 712.8. Blood work is normal.",
    delta: { radius_mean: 15.1, texture_mean: 22.02, perimeter_mean: 97.26, area_mean: 712.8 },
  },
  {
    id: "breast-15",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 17.3 and an area of 928.2. Blood work is normal.",
    delta: { radius_mean: 17.3, texture_mean: 17.08, perimeter_mean: 113, area_mean: 928.2 },
  },
  {
    id: "breast-16",
    domain: "Breast",
    expect: "Breast",
    positive: true,
    source: "Wisconsin Diagnostic Breast Cancer, positive record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 16.02 and an area of 797.8. Blood work is normal.",
    delta: { radius_mean: 16.02, texture_mean: 23.24, perimeter_mean: 102.7, area_mean: 797.8 },
  },
  {
    id: "breast-neg-17",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 9.504 and an area of 273.9. Blood work is normal.",
    delta: { radius_mean: 9.504, texture_mean: 12.44, perimeter_mean: 60.34, area_mean: 273.9 },
  },
  {
    id: "breast-neg-18",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 6.981 and an area of 143.5. Blood work is normal.",
    delta: { radius_mean: 6.981, texture_mean: 13.43, perimeter_mean: 43.79, area_mean: 143.5 },
  },
  {
    id: "breast-neg-19",
    domain: "Breast",
    expect: "No cancer detected",
    positive: false,
    source: "Wisconsin Diagnostic Breast Cancer, negative record",
    note: "55 year old woman. Biopsy imaging shows a nuclear radius of 11.43 and an area of 398. Blood work is normal.",
    delta: { radius_mean: 11.43, texture_mean: 17.31, perimeter_mean: 73.66, area_mean: 398 },
  },
  {
    id: "liver-20",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "18 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 18, protein_total: 6.8, albumin: 3.6, ast: 36, alt: 35, bilirubin: 1.8, alkaline_phosphatase: 178, gender: 1 },
  },
  {
    id: "liver-21",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "22 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 22, protein_total: 8, albumin: 3.9, ast: 41, alt: 78, alkaline_phosphatase: 202, gender: 1 },
  },
  {
    id: "liver-22",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "30 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 30, protein_total: 5.6, albumin: 2.7, ast: 139, alt: 84, bilirubin: 1.6, alkaline_phosphatase: 332, gender: 1 },
  },
  {
    id: "liver-23",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "32 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 32, protein_total: 6, albumin: 2.9, ast: 190, alt: 102, bilirubin: 0.7, alkaline_phosphatase: 276, gender: 1 },
  },
  {
    id: "liver-24",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "38 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 38, protein_total: 6, albumin: 3, ast: 48, alt: 89, bilirubin: 1.7, alkaline_phosphatase: 859, gender: 1 },
  },
  {
    id: "liver-25",
    domain: "Liver",
    expect: "Liver",
    positive: true,
    source: "Hepatocellular cohort, positive record",
    note: "62 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 62, protein_total: 8.6, albumin: 4, ast: 155, alt: 69, bilirubin: 1.8, alkaline_phosphatase: 224, gender: 1 },
  },
  {
    id: "liver-neg-26",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "Hepatocellular cohort, negative record",
    note: "17 year old woman with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 17, protein_total: 7.1, albumin: 4.5, ast: 21, alt: 28, bilirubin: 0.5, alkaline_phosphatase: 206 },
  },
  {
    id: "liver-neg-27",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "Hepatocellular cohort, negative record",
    note: "29 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 29, protein_total: 6.8, albumin: 3.7, ast: 15, alt: 12, bilirubin: 0.8, alkaline_phosphatase: 156, gender: 1 },
  },
  {
    id: "liver-neg-28",
    domain: "Liver",
    expect: "No cancer detected",
    positive: false,
    source: "Hepatocellular cohort, negative record",
    note: "28 year old man with no viral hepatitis or cirrhosis on record. AFP at 3.1 ng/mL.",
    delta: { age: 28, albumin: 3.5, ast: 16, alt: 15, alkaline_phosphatase: 159, gender: 1 },
  },
  {
    id: "pancreatic-29",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "31 year old man. CA 19-9 at 334.735 U/mL, bilirubin 1.6069, glucose 99.93, creatinine 1.5987.",
    delta: { age: 31, glucose: 99.93, creatinine: 1.5987, bilirubin: 1.6069, plasma_ca19_9: 334.7348, gender: 1 },
  },
  {
    id: "pancreatic-30",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "49 year old woman. CA 19-9 at 303.428 U/mL, bilirubin 3.2066, glucose 130.85, creatinine 1.3822.",
    delta: { age: 49, glucose: 130.85, creatinine: 1.3822, bilirubin: 3.2066, plasma_ca19_9: 303.4284 },
  },
  {
    id: "pancreatic-31",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "74 year old woman. CA 19-9 at 461.786 U/mL, bilirubin 1.0744, glucose 122.54, creatinine 1.6178.",
    delta: { age: 74, glucose: 122.54, creatinine: 1.6178, bilirubin: 1.0744, plasma_ca19_9: 461.786 },
  },
  {
    id: "pancreatic-32",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "50 year old woman. CA 19-9 at 377.127 U/mL, bilirubin 2.3407, glucose 83.7, creatinine 1.3564.",
    delta: { age: 50, glucose: 83.7, creatinine: 1.3564, bilirubin: 2.3407, plasma_ca19_9: 377.1267 },
  },
  {
    id: "pancreatic-33",
    domain: "Pancreatic",
    expect: "Pancreatic",
    positive: true,
    source: "Pancreatic biomarker cohort, positive record",
    note: "31 year old man. CA 19-9 at 310.02 U/mL, bilirubin 2.8241, glucose 68.24, creatinine 1.6912.",
    delta: { age: 31, glucose: 68.24, creatinine: 1.6912, bilirubin: 2.8241, plasma_ca19_9: 310.0204, gender: 1 },
  },
];

export const caseValues = (c: DemoCase): CaseValues => ({ ...NORMAL, ...c.delta });

/** Draw a random case, never the same one twice in a row. */
export function randomCase(previousId?: string): DemoCase {
  const options = CASE_POOL.filter(c => c.id !== previousId);
  return options[Math.floor(Math.random() * options.length)];
}

/**
 * The case the page opens on. Fixed rather than random so the first render
 * matches between server and client. Every press of Generate case after that
 * draws at random.
 */
export const OPENING_CASE = CASE_POOL.find(c => c.id === "breast-14")!;
